name: Devops class start github

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ownserver
    steps:
      - name: print hello world
        run: |
         echo "hello world"
         hostname
         ip a

